dataset: # dataset to run benchmark on
  - leukemia
  - simulated

solver: # list of example solvers to do benchmark
  - cd
  - snapml
  - lightning
  - glmnet
  - sklearn

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
